// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf1J0g3auud7pivzHqmqrl0bxrEg_bQNo',
    appId: '1:469192533881:web:ce941872b3d3418c96b1a8',
    messagingSenderId: '469192533881',
    projectId: 'one-theatre-01',
    authDomain: 'one-theatre-01.firebaseapp.com',
    storageBucket: 'one-theatre-01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdeUOTuSxY-ezwI72c6LpZC-ysJsh7DFU',
    appId: '1:469192533881:android:d2f951a70fabeb2496b1a8',
    messagingSenderId: '469192533881',
    projectId: 'one-theatre-01',
    storageBucket: 'one-theatre-01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgD1Tu65cbrbzcmMHBaoHRZ21t3QjeKX0',
    appId: '1:469192533881:ios:64245fb66c5752f896b1a8',
    messagingSenderId: '469192533881',
    projectId: 'one-theatre-01',
    storageBucket: 'one-theatre-01.appspot.com',
    iosBundleId: 'com.onetheatre.onetheatre',
  );
}
